### ISSUE TITLE
Python.h: No such file or directory

### ISSUE THREAD

**Issue by palayo** [danjperron/BitBangingDS18B20#12]
I read some DS18B20 sensors using w1 on raspberry pi 3 B+.
However, the /sys/bus/w1/devices/28-* directories suddenly disappear within a few hours after boot and I need to unplug the power to reset. It only happens with one raspi and not with others. I could not find out the reason which may be in sensors or raspbian stretch...
Now I'm considering to use BitBangingDS18B20.
I could compile and run the command, it works!
$ ./DS18B20Scan -gpio 10
28-0310979469A4 : 12 bits  Temperature:  25.62 +/- 0.06 Celsius
28-030897940675 : 12 bits  Temperature:  25.19 +/- 0.06 Celsius

Then I tried to install python add-on but an error occured. 
Please tell me how to fix it.
# python3 setup.py install
running install
running build
running build_ext
building 'DS18B20' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/us

r/include/python3.5m -c DS18B20.c -o build/temp.linux-armv7l-3.5/DS18B20.o
DS18B20.c:12:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

**Comment by danjperron** [comment]
Hi palayo,

 You didn't  told me which O.S. you are using.

I assume that is debian buster light!

First download the latest buster, 10 of July, since the version of June isn't a stable version.

On the light version you need to install some libraries.

`sudo apt-get update`
`sudo apt-get install git python3-distutils python3-dev`

P.S. I didn't check my code on the PI4.

**Comment by palayo** [comment]
>danjperron
Thanks for your reply.
The OS is raspbian 4.14.98-v7+.
I installed python3-dev then I could finish "python3 setup.py install" command without error.
However, when the /sys/bus/w1/devices/28-* directories disappear, even your command "./DS18B20Scan -gpio 10" cannot get the temparatures.
I don't understand why the sensors  will suddenly disappear within a few hours after boot.
If you have any knowledge, please let me know.

**Comment by danjperron** [comment]
> I don't understand why the sensors will suddenly disappear.

Could Be a bad contact, a bad sensor or too much resistivity or capacitance on the cable.

Try to split in half your cable and check which side of the newly 2 cables is the problem. 

My code and the normal 1-wires driver work with two GPIOs.
