### ISSUE TITLE
python.h not found

### ISSUE THREAD

**Issue by MartinSwanepoel** [danjperron/BitBangingDS18B20#14]
sudo python setup.py install
running install
running build
running build_ext
building 'DS18B20' extension
creating build
creating build/temp.linux-armv6l-2.7
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-InigCj/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c DS18B20.c -o build/temp.linux-armv6l-2.7/DS18B20.o
DS18B20.c:12:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

**Comment by MartinSwanepoel** [comment]
Solution:

sudo apt-get install python-dev
sudo apt-get install python3-dev

**Comment by danjperron** [comment]
Thanks Martin!  I added the installation of python-dev into the readme
