### ISSUE TITLE
many sensors

### ISSUE THREAD

**Issue by useapp** [danjperron/BitBangingDS18B20#17]
with two sensors all work corectly if i connect 7 sensors i have unclear response

./DS18B20Scan -gpio 4 

28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  69.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  21.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius
28-0000090E6B5A:09 bits  Temperature:  85.00 +/- 0.50 Celsius

**Comment by danjperron** [comment]
HI andžej,

  Multiple thing could be problematic.  Often this is a cable problem.  Inductance from the cable could create long rising and falling time signal .  The lenght of the cable is also an issue. Wire gauge  alos  create too much resistance.  Cross talk betweens wires create noise.  Wire passing near power cable, motors or contactor could create gliches. A bad sensor could also be the problem.   If you are using my code on a single line bus check the original code provided with the Raspberry Pi and see if you have the same problem.

My code was made to increase  the readout speed  and use multiple GPIO at the same time.   The problem isn't too many sensor but every thing else needs to be checked. Use an oscilloscope to check the signal. This is the best instrument to figure out the problem.

B.T.W. this is a link to show 30 sensors working fine.  It is in french,
https://www.youtube.com/watch?v=PLcpTW5cTKU

**Comment by danjperron** [comment]
Got new code for Pi5 . CLose old issue.
