### ISSUE TITLE
Changes Back to 12 Bits

### ISSUE THREAD

**Issue by mikebertiean** [danjperron/BitBangingDS18B20#7]
Hey!
I have a pi 3 model B which I am trying to update the resolution to 10 bits instead of the default 12. 

I got your script, and updated the BASE to 0x3F000000. 
The script ran fine and I saw that the w1_slave file has been updated correctly.

The problem comes in after reading the temp for a few seconds, it always switches back to 12 bit. 

Any ideas on why it is not staying set? The first couple of seconds it works as expected.

Thanks!

**Comment by danjperron** [comment]
You are using the 1wire driver!  Then it will automatically switch the sensor to 12bits.

If you want faster rate  use DS18B20Scan.  But use another pin than the 1wire.  Together they won't work!

**Comment by mikebertiean** [comment]
Did some research, but I am not entirely sure what the 1wire driver is? 
Right now we have it hooked up on GPIO 4, if I change it to a different standard GPIO it should be okay?

**Comment by danjperron** [comment]
"w1_slave"  only show if you have the 1wire driver.  

check /boot/config.txt and you will have a line like  
dtoverlay=w1-gpio


This github  application was meant to  read the sensor faster than the 1wire driver could do.  You are out of the 1 wire system.  Only one of my two applications could read the sensor that way unless you hook it up to an arduino or something similar.

When you  set the sensor to 10 bits  , you write into the build-in eerom but it could be rewritten by the 1wire driver on the raspberry pi.
